spring:
  datasource:
    url: ${TEST_DB_URL:jdbc:mysql://localhost:3306/lumu99_forum_test?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai}
    username: ${TEST_DB_USERNAME:root}
    password: ${TEST_DB_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      initialization-fail-timeout: -1
  flyway:
    enabled: false
